In [ ]:
import numpy as np
import gym
import random
from IPython.display import clear_output
import time



In [ ]:
env=gym.make("FrozenLake-v1")

In [ ]:
action_space_size=env.action_space.n
state_space_size=env.observation_space.n

q_table=np.zeros((state_space_size,action_space_size))
print(q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
num_episode=10
max_steps_per_episode=100

learning_rate=0.1
discount_rate=0.99

exploration_rate=1
max_exploration_rate=1

min_exploration_rate=0.01
exploration_decay_rate=0.01

In [ ]:
for episode in range(num_episode):
    state = env.reset()
    # if isinstance(state, tuple):
    #     state = state[0]
    done = False
    print("*****Episode ", episode + 1, "*********\n\n\n")
    time.sleep(1)

    for step in range(max_steps_per_episode):
        clear_output(wait=True)
        env.render()
        time.sleep(0.3)

        action = np.argmax(q_table[state, :])
        new_state, reward, done, info = env.step(action)

        if done:
            clear_output(wait=True)
            env.render()
            if reward == 1:
                print("Goal Reached!")
                time.sleep(3)
            else:
                print("You fell through a hole!")
                time.sleep(3)
            clear_output(wait=True)
            break

        state = new_state

env.close()

You fell through a hole!
